### ISSUE TITLE
opencv error

### ISSUE THREAD

**Issue by cherryxiongyw** [chuanqi305/MobileNet-SSD#105]
When I run ./train.sh, I got error as:
`
OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F)) in cvtColor, file /home/amax/opencv-3.2.0/modules/imgproc/src/color.cpp, line 9815
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/amax/opencv-3.2.0/modules/imgproc/src/color.cpp:9815: error: (-215) (scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F) in function cvtColor

*** Aborted at 1530956265 (unix time) try "date -d @1530956265" if you are using GNU date ***
`
what can i do ?

**Comment by neos2008** [comment]
@cherryxiongyw  how do you fix this problem?

**Comment by matthiaskiller** [comment]
@cherryxiongyw @neos2008  i have the same issue 
did you find a way to fix the problem?

**Comment by Mycenae** [comment]
Some say that it is because some images in the dataset has 1 channel (gray image) , and the width and height of some image is less than 300 (or 512 depending on which model you use); I checked the dataset, and eliminate these images, but still I got this problem, so I think there must be something else also caused it.
see: https://blog.csdn.net/10km/article/details/70160645
